### ISSUE TITLE
getLoggedInAthleteActivites does not respect per_page parameter

### ISSUE THREAD

**Issue by ted-piotrowski** [rfoel/strava#112]
The following request should return one activity but returns the default 30:

```
await strava.activities.getLoggedInAthleteActivities({ per_page: 1 });
```

Same when requesting LatLng key in Streams, only the default distance stream is returned:

```
await strava.streams.getActivityStreams({ id: 5937416221, keys: [StreamKeys.LatLng] });
```

This behavior works as intended in 1.3.2, so it broken recently. I believe it's related to this change:

https://github.com/rfoel/strava/blob/main/src/request.ts#L54

Specifically, the new query serialisation code results in urls of the following format `/athlete/activities?query=%5Bobject+Object%5D`

Current workaround is to downgrade to 1.3.2.

**Comment by rfoel** [comment]
I'll check that out!

**Comment by rfoel** [comment]
I fixed this bug and I will release the fix soon. I added tests to all endpoints to make sure the correct request is being sent.

Also I decided to make a breaking change to the api, so when you used 
```js
await strava.streams.getActivityStreams({ id: 5937416221, keys: [StreamKeys.LatLng] });
```
you can simply replace with
```js
await strava.streams.getActivityStreams({ id: 5937416221, keys: 'latlng' });
// or 
await strava.streams.getActivityStreams({ id: 5937416221, keys: ['latlng'] });
```
It should autocomplete with the available keys for you now.
