### ISSUE TITLE
Improve Oauth  management 

### ISSUE THREAD

**Issue by thibaultleouay** [rfoel/strava#178]
hey, 

It would be super useful if the client could take an access_token parameter 

Also it would be great if there was some methods to refresh the token 

That would be my workflow 
1- strava.oauth.refreshToken -> return the new Token 
2 - strava.something({access_token}) 
3- strava.otherMethod({access_token}) 
4- store access token  

I will provide a PR if it's ok

**Comment by rfoel** [comment]
@thibaultleouay hey, thank you for your contribuition.

The way the client is implemented it already refreshes the token when needed. What is your use case to refresh it manually? 
I really want to improve the way the oauth works for this lib, but I haven't got much time lately. Feel free to send a PR and I will take a look.

**Comment by thibaultleouay** [comment]
Yep it does refresh the token, 
But I also want to be able to store the new token :) 


Exactly as it's shown in the strava doc 

![image](https://user-images.githubusercontent.com/13894054/204556000-4c9cb3c8-a9c4-4aea-b4e7-a25f53ff00ad.png)

**Comment by rfoel** [comment]
Ah I see. Feel free to work on that.
