### ISSUE TITLE
Missing type in resouces/uploads.ts

### ISSUE THREAD

**Issue by OtaK** [rfoel/strava#6]
The `File` type present here doesn't resolve to any imports or anything, is this still a WIP?

![image](https://user-images.githubusercontent.com/1262712/101934371-cabb0f00-3bdd-11eb-83f5-60d4834ef5f0.png)

**Comment by rfoel** [comment]
Probably it's missing `@types/node`. This is a native File definition. How did you get this error?

**Comment by OtaK** [comment]
Just running `tsc` in another TypeScript project including the library.

extracted from my tsconfig.json:

```json
"compilerOptions": {
    "allowUnreachableCode": false,
    "allowUnusedLabels": false,
    "noImplicitAny": true,
    "forceConsistentCasingInFileNames": true,
    "noEmitOnError": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "pretty": true,
    "module": "CommonJS",
    "lib": ["ES2020", "esnext.asynciterable"],
    "target": "ES2020",
    "moduleResolution": "node",
    "incremental": true,
    "sourceMap": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "outDir": "build",
    "baseUrl": ".",
    "newLine": "LF"
},

```

**Comment by rfoel** [comment]
I see. I'm no expert on Typescript and haven't tested on a project only using node. The file type perhaps could be either a File or a Buffer?

**Comment by OtaK** [comment]
I've created a fork and made some changes. From what I can see there were a couple of errors (in particular trying to `JSON.stringify` a multipart request body, which doesn't work in the browser or node) and missing types. If you want to take a look, the changes are here: https://github.com/rfoel/strava/compare/main...OtaK:main

With those changes I get to a point where only the `@types/strava` definitions are missing so it seems the module itself does compile successfully. 
![image](https://user-images.githubusercontent.com/1262712/101938952-8ed77800-3be4-11eb-98a3-0bf32cb81245.png)

**Comment by rfoel** [comment]
Great! 
I'm pretty sure the `node-fetch` has a Blob class, so you don't have to add that as a dependency, not sure about FormData though. 

Also, I'm not sure what Strava types are missing.

**Comment by rfoel** [comment]
I added the types property to the package.json, so it should be fine this last issue. Also, I changed the type of the file to Blob.
